#!/bin/sh
# (C) 2019 openwrt.org
# wget https://raw.githubusercontent.com/lihaixin/openwrt-docker-builder/master/sbin/help -O /sbin/help
get_ip () {
    # 修改主机全名
    npsip=""
    while $npsip
        do
            npsip=$(dig nps.15099.net +short | grep ^[0-9]| head -n 1 | sed s'/.$//')
            sleep 20
        done
    
    frpdomain=""
    while $frpdomain
        do
            frpdomain=$(dig frp.15099.net +short | grep ^[a-z]| head -n 1 | sed s'/.$//')
            sleep 20
        done
}

get_ip

hfrp () {
    # 调整帮助frp信息
    killall hfrpc
    if [ ! -f "/var/sbin/hfrpc" ];then
        cp /usr/bin/frpc /var/sbin/hfrpc
    fi
    if [ ! -f "/var/etc/frp/hfrpc.log" ];then
        touch /var/etc/frp/hfrpc.log
    fi
    if [ ! -d "/var/etc/frp" ];then
        mkdir -p /var/etc/frp
    fi
    routename=`uci get system.@system[0].hostname`
    lanipaddr=`uci get network.lan.ipaddr`

cat > /var/etc/frp/hfrpc.conf<< TEMPEOF
[common]
server_addr=$frpdomain
server_port=443
token=kbEwlNnKytsg28gfvseCmP5pU8Vqo0c1rrlHfsi3Q
log_level=info
log_max_days=3
protocol=tcp
log_file=/var/etc/frp/hfrpc.log
pool_count=2
tcp_mux=true
login_fail_exit=false

[$routename-https]
type=https
subdomain=$routename-https
local_ip=$lanipaddr
local_port=44344
use_encryption=true
use_compression=true

[$routename-ttyds]
type=https
subdomain=$routename-ttyds
local_ip=$lanipaddr
local_port=7682
use_encryption=true
use_compression=true
TEMPEOF

/var/sbin/hfrpc -c /var/etc/frp/hfrpc.conf &
}

hfrp

frp () {
    if [ -f /etc/rc.d/S99frp ] && [ `uci get frp.common.enabled` = 1 ] && [ `uci get frp.common.server_addr` = 127.0.0.1 ]; then
    /etc/init.d/tcpproxy stop > /dev/null 2>&1
    sleep 1
    /etc/init.d/tcpproxy start > /dev/null 2>&1
    routename=`uci get system.@system[0].hostname`
    lanipaddr=`uci get network.lan.ipaddr`
    rm -rf /etc/config/frp
    touch /etc/config/frp
    uci set frp.common=frp
    uci set frp.common.log_max_days='3'
    uci set frp.common.login_fail_exit='0'
    uci set frp.common.vhost_http_port='80'
    uci set frp.common.vhost_https_port='443'
    uci set frp.common.server_port='7000'
    uci set frp.common.log_level='info'
    uci set frp.common.server_addr='127.0.0.1'
    uci set frp.common.token='kbEwlNnKytsg28gfvseCmP5pU8Vqo0c1rrlHfsi3Q'
    uci set frp.common.enabled='1'
    uci set frp.common.time='40'
    uci set frp.common.tcp_mux='1'
    uci set frp.common.protocol='tcp'
    uci set frp.common.enable_http_proxy='0'
    uci set frp.common.enable_cpool='1'
    uci set frp.common.pool_count='2'

    uci add frp proxy
    uci set frp.@proxy[0].enable='1'
    uci set frp.@proxy[0].type='http'
    uci set frp.@proxy[0].domain_type='subdomain'
    uci set frp.@proxy[0].local_port='80'
    uci set frp.@proxy[0].local_ip=$lanipaddr
    uci set frp.@proxy[0].use_encryption='1'
    uci set frp.@proxy[0].use_compression='1'
    uci set frp.@proxy[0].remark=$routename-http
    uci set frp.@proxy[0].subdomain=$routename

    uci add frp proxy
    uci set frp.@proxy[1].enable='1'
    uci set frp.@proxy[1].type='http'
    uci set frp.@proxy[1].domain_type='subdomain'
    uci set frp.@proxy[1].local_port='7681'
    uci set frp.@proxy[1].local_ip=$lanipaddr
    uci set frp.@proxy[1].use_encryption='1'
    uci set frp.@proxy[1].use_compression='1'
    uci set frp.@proxy[1].remark=$routename-ttyd
    uci set frp.@proxy[1].subdomain=$routename-ttyd

    uci commit frp
    /etc/init.d/frp stop
    /etc/init.d/frp start
    sed -i 's/<%=luci.sys.hostname() or "?"%></<%=luci.sys.hostname() or "?"%>.'`echo $frpdomain`'</g' /usr/lib/lua/luci/view/admin_status/index.htm
fi

# 隐藏（强制关闭）frp界面
# if [ -f "/usr/lib/lua/luci/controller/frp.lua" ];then
# mv /usr/lib/lua/luci/controller/frp.lua /usr/lib/lua/luci/controller/frp.lua.bak
# sleep 1
# /etc/init.d/uhttpd restart
# fi 
}

frp

oversea () {
    # 调整更新海外模式
    if [ `uci get shadowsocksr.@global[0].run_mode` = oversea ];then
        uci delete shadowsocksr.@access_control[0].wan_fw_ips
        uci commit shadowsocksr
        sed -i s'/www.google.com/ip111.cn/g' /usr/bin/ssr-switch
        custom_oversea_url=$(cat /etc/rc.local | grep  -v ^# | grep custom_oversea_url | cut -c20-)
        if [ ! $custom_oversea_url ];then
            /usr/bin/wget-ssl -O /etc/config/oversea_list.conf https://raw.githubusercontent.com/coolsnowwolf/lede/master/package/lean/luci-app-ssr-plus/root/etc/dnsmasq.oversea/oversea_list.conf > /dev/null 2>&1
            if [ -s "/etc/config/oversea_list.conf" ];then
                cat /etc/config/oversea_list.conf > /etc/dnsmasq.oversea/oversea_list.conf
            fi
        else
           /usr/bin/wget-ssl -O /etc/config/oversea_list.ip $custom_oversea_url > /dev/null 2>&1
           if [ -s "/etc/config/oversea_list.ip" ];then
                cat /etc/config/oversea_list.ip | grep  ^- | sort | uniq | sed s'/.$/\/8.8.8.8#53/' |sed s'/^-/server=\//' > /etc/dnsmasq.oversea/oversea_list.conf
                cat /etc/config/oversea_list.ip | grep -v ^# | grep -v ^- | sort | uniq | sed s'/.$/\/127.0.0.1#5335/' |sed s'/^/server=\//' >> /etc/dnsmasq.oversea/oversea_list.conf
                cat /etc/config/oversea_list.ip | grep -v ^# | grep -v ^- | sort | uniq | sed s'/.$/\/oversea/' |sed s'/^/ipset=\//' >> /etc/dnsmasq.oversea/oversea_list.conf
           fi
        fi
        sleep 2
        /etc/init.d/shadowsocksr restart
    fi
    
    if [ `uci get shadowsocksr.@global[0].run_mode` = router ];then
        uci delete shadowsocksr.@access_control[0].wan_fw_ips
        sed -i s'/ip111.cn/www.google.com/g' /usr/bin/ssr-switch
        uci add_list shadowsocksr.@access_control[0].wan_fw_ips='149.154.160.0/20' 
        uci add_list shadowsocksr.@access_control[0].wan_fw_ips='67.198.55.0/24' 
        uci add_list shadowsocksr.@access_control[0].wan_fw_ips='91.108.4.0/22' 
        uci add_list shadowsocksr.@access_control[0].wan_fw_ips='91.108.56.0/22' 
        uci add_list shadowsocksr.@access_control[0].wan_fw_ips='109.239.140.0/24' 
        uci add_list shadowsocksr.@access_control[0].wan_fw_ips='198.13.38.188/32'
        uci commit shadowsocksr
        sleep 2
        /etc/init.d/shadowsocksr restart
    fi
}

oversea

nps () {
    # 启动nps服务
    if [ -f /etc/rc.d/S50nps ] && [ `uci get nps.@nps[0].enabled` = 1 ] && [ `uci get nps.@nps[0].server_addr` = 127.0.0.1 ]; then
    /etc/init.d/tcpproxy stop > /dev/null 2>&1
    sleep 1
    /etc/init.d/tcpproxy start > /dev/null 2>&1
    uci set nps.@nps[0].protocol='tcp'
    uci set nps.@nps[0].compress='1'
    uci set nps.@nps[0].crypt='1'
    uci set nps.@nps[0].log_level='4'
    uci set nps.@nps[0].vkey='kbEwlNnKytsg28gfvseCmP5pU8Vqo0c1rrlHfsi3Q'
    uci set nps.@nps[0].server_port='8024'
    uci commit nps
    sleep 2
    /etc/init.d/nps stop
    /etc/init.d/nps start
    fi
}

nps
