#!/bin/sh
# (C) 2019 openwrt.org

for i in $(seq 1 2 1000)
do
   echo -e "\n"
   echo clear route dns cache:
   pdnsd-ctl -c /var/dnscache/ empty-cache > /dev/null 2>&1
   pdnsd-ctl -c /var/pdnsd empty-cache > /dev/null 2>&1
   sleep 5
   echo check access china IP:
   echo -e "acccess 3322.org ip is:\c" && curl http://members.3322.org/dyndns/getip
   sleep 2
   echo -e "\n"
   echo check access google IP:
   ip111cn=$(curl http://ip111cn.appspot.com/ 2>/dev/null)
   echo -e "acccess ip111.cn ip is:\c" && echo $ip111cn | sed 's/<html><head><meta charset="utf-8"><\/head><body style="text-align: center; font-family: Helvetica,Arial,sans-serif; font-size: 14px; ">//' | sed 's/<\/body><\/html>//'
   ip100info=$(curl http://ip100info.appspot.com/ip.php 2>/dev/null)
   echo -e "acccess ip100.info ip is:\c" && echo $ip100info | sed 's/<br>//'
   sleep 2
   echo -e "\n"
   echo check access overseas IP:
   echo -e "acccess ifconfig.me ip is:\c" && curl ifconfig.me
   echo
   echo -e "acccess ipinfo.io ip is:\c" && curl ipinfo.io/ip
   echo -e "acccess whatismyip.akamai.com ip is:\c" && curl whatismyip.akamai.com
   echo
   echo -e "acccess ip.sb ip is:\c" && curl ip.sb
done
